name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run Tests
      - name: Run Tests
        run: ./gradlew test

      # Assemble Application
      - name: Build Project
        run: ./gradlew assemble